name: mac

on:
    workflow_dispatch:

jobs:
    build-mac:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - uses: actions/checkout@v1
            - name: setup
              run: |
                  cd ../..
                  git clone https://github.com/open-ephys/plugin-GUI.git --branch main
                  cd plugin-GUI/Build && cmake -G "Xcode" ..
            - name: build
              run: |
                  git submodule update --init
                  cd Build
                  cmake -G "Xcode" ..
                  xcodebuild -configuration Release
            #    - name: test
            #      run: cd build && ctest
            - name: deploy
              env:
                  artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
                  build_dir: "Build/Release"
                  package: XDAQ-mac
              run: |
                  plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]" | tail -1)
                  tag=$(git describe --tags $(git rev-list --tags --max-count=1))
                  new_plugin_ver=$tag-API$plugin_api
                  mkdir plugins 
                  cp -r $build_dir/*.bundle plugins
                  mkdir shared	
                  cp third_party/FrontPanel/libokFrontPanel.dylib shared
                  cp Resources/xdaq.bit shared
                  zipfile=${package}_${new_plugin_ver}.zip
                  zip -r -X $zipfile plugins shared
                  echo curl -H "X-JFrog-Art-Api:$artifactoryApiKey" -T $zipfile "https://openephys.jfrog.io/artifactory/XDAQ-plugin/mac/$zipfile"
                  mkdir repacked
                  mv $zipfile repacked
        
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: mac
                  path: repacked/*.zip
