name: Windows

on:
    workflow_dispatch:

jobs:
    build-windows:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-2022]

        steps:
            - uses: actions/checkout@v1
            - name: setup
              env:
                  repo: open-ephys-gui
                  package: "open-ephys-lib"
              run: |
                  cd ../..
                  git clone https://github.com/open-ephys/plugin-GUI.git --branch main
                  cd plugin-GUI/Build
                  cmake -G "Visual Studio 17 2022" -A x64 ..
                  mkdir Release && cd Release
                  curl -L https://openephysgui.jfrog.io/artifactory/Libraries/open-ephys-lib-v0.6.0.zip --output open-ephys-lib.zip 
                  unzip open-ephys-lib.zip
              shell: bash
            - name: configure
              run: |
                  git submodule update --init
                  cd Build
                  cmake -G "Visual Studio 17 2022" -A x64 ..
              shell: bash
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1
            - name: build-plugin
              run: |
                  cd Build
                  msbuild ALL_BUILD.vcxproj -p:Configuration=Release -p:Platform=x64
              shell: cmd
            #    - name: test
            #      run: cd build && ctest
            - name: deploy
              env:
                  artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
                  build_dir: "Build/Release"
                  package: XDAQ-windows
              run: |
                  plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
                  tag=$(git describe --tags $(git rev-list --tags --max-count=1))
                  new_plugin_ver=$tag-API$plugin_api
                  mkdir plugins
                  cp $build_dir/*.dll plugins
                  mkdir shared
                  cp third_party/FrontPanel/okFrontPanel.dll shared
                  cp Resources/xdaq.bit shared
                  zipfile=${package}_${new_plugin_ver}.zip
                  powershell Compress-Archive -Path "plugins" -DestinationPath ${zipfile}
                  powershell Compress-Archive -U -Path "shared" -DestinationPath ${zipfile}
                  echo curl -H "X-JFrog-Art-Api:$artifactoryApiKey" -T $zipfile "https://openephys.jfrog.io/artifactory/XDAQ-plugin/windows/$zipfile"
                  mkdir repacked
                  mv $zipfile repacked
              shell: bash
            
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: windows
                  path: repacked/*.zip